### ISSUE TITLE
[feature request] visual filters

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlockServer#447] opened 2022-01-12 20:01 UTC
hi, this is in no way an actual request/demand, 
but more of an early stage idea, 
gracefully "dumped" here for some creative brain storming.. (so feel free to close it..).

<hr/> 

There is a growing trend of YouTubers making poor (not to mention annoying) use of the screen.

here is an example:  
<img width="400" alt="2022-01-12_212749" src="https://user-images.githubusercontent.com/415238/149208450-79bd9446-4425-442a-a87e-ea98663ad121.png">

<hr/>

I though some time now of some visual filters,  
implementation can be a div, solid-filled color (user may select the color to match the video's actual background), placed in top-most z-index order (or at least above the playing-video layer),  
it can stay there for a specific time, similar to how all the existing filter already work (but obviously it also requires holding an additional placement-data, top-left, height, width or something like that).

it is also similar to the way the YT-player implements over-the-video banners.

here is quick and dirty "mock" (using some graphic editor):  

https://user-images.githubusercontent.com/415238/149212087-590f1754-9ebb-458b-9702-4c8ddf9a5d25.mp4

<hr/>

a possible extended visual filter can stretch the video, 
from a point, to fill the current video container.

https://user-images.githubusercontent.com/415238/149212553-14f6bc8e-2192-4dbd-bd8c-fa5814d774a3.mp4

stored data would probably require the square measurements, and starting-ending times again.

<hr/>

**Comment by ajayyy** [comment] 2022-01-12 20:32
Duplicate of https://github.com/ajayyy/SponsorBlock/issues/538

Draft pull request implementation I started last fall, there is some description about what I was planning there: https://github.com/ajayyy/SponsorBlock/pull/971

**Closed by ajayyy** 2022-01-12 20:32 UTC
