### ISSUE TITLE
[Suggestion] When submitter downvote himself, the segment should be deleted

### ISSUE THREAD

**Issue by RisedSky** [ajayyy/SponsorBlockServer#359] opened 2021-09-05 11:26 UTC
It will save disk space. 
Or, we can still improve this idea by deleting the segment in 30 days, so if the submitter is doing bad segments, the mod team can still moderate until the segment is flushed

**Comment by ajayyy** [comment] 2021-09-05 17:13
Duplicate of https://github.com/ajayyy/SponsorBlockServer/issues/221

**Closed by ajayyy** 2021-09-05 17:13 UTC
